# Generated by Django 3.2.9 on 2021-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('efname', models.CharField(max_length=20)),
                ('elname', models.CharField(max_length=20)),
                ('edob', models.DateField()),
                ('email', models.EmailField(max_length=40)),
                ('eaddr', models.TextField()),
                ('ephone', models.BigIntegerField()),
            ],
        ),
    ]
